{% set name = "ucs-detect" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace("-", "_") }}-{{ version }}.tar.gz
  sha256: bb590960fd20684a2dd6ec2bfa924ce0d8dfdb7bce77caeaf38f7697f76dddde

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - ucs-detect=ucs_detect:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - blessed >=1.17.6,<2

test:
  imports:
    - ucs_detect

about:
  home: https://github.com/jquast/ucs-detect/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Detects the Unicode Version of an interactive terminal for export'
  dev_url: https://github.com/jquast/ucs-detect/

extra:
  recipe-maintainers:
    - scopatz
